"""Add indexes to models

Revision ID: 57a86e38bb92
Revises: bddc38769ebc
Create Date: 2025-01-25 11:30:23.063376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a86e38bb92'
down_revision = 'bddc38769ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Incidents Table
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_wilaya'), ['wilaya'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_commune'), ['commune'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_localite'), ['localite'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_structure_type'), ['structure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_nature_cause'), ['nature_cause'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_date_incident'), ['date_incident'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_gravite'), ['gravite'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_date_resolution'), ['date_resolution'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_center_id'), ['center_id'], unique=False)

    # Users Table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_zone_id'), ['zone_id'], unique=False)

    # User Profiles Table
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_profiles_professional_number'), ['professional_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_profiles_job_function'), ['job_function'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_recruitment_date'), ['recruitment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=False)

    # Units Table
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_units_zone_id'), ['zone_id'], unique=False)

    # Zones Table
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_zones_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Zones Table
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_code'))
        batch_op.drop_index(batch_op.f('ix_zones_name'))

    # Units Table
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_zone_id'))
        batch_op.drop_index(batch_op.f('ix_units_code'))
        batch_op.drop_index(batch_op.f('ix_units_name'))

    # User Profiles Table
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_recruitment_date'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_professional_number'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_job_function'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_first_name'))

    # Users Table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_zone_id'))
        batch_op.drop_index(batch_op.f('ix_users_unit_id'))
        batch_op.drop_index(batch_op.f('ix_users_last_login'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    # Incidents Table
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_center_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_unit_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_date_resolution'))
        batch_op.drop_index(batch_op.f('ix_incidents_gravite'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_date_incident'))
        batch_op.drop_index(batch_op.f('ix_incidents_nature_cause'))
        batch_op.drop_index(batch_op.f('ix_incidents_structure_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_localite'))
        batch_op.drop_index(batch_op.f('ix_incidents_commune'))
        batch_op.drop_index(batch_op.f('ix_incidents_wilaya'))
        batch_op.drop_index(batch_op.f('ix_incidents_title'))

    # ### end Alembic commands ###
