"""initial migration

Revision ID: 58a64db92631
Revises: 
Create Date: 2024-12-09 20:59:43.028873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a64db92631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use batch_alter_table to handle existing tables
    with op.batch_alter_table('zones', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_zones', ['id'])
        batch_op.create_unique_constraint('uq_zones_code', ['code'])
        batch_op.create_unique_constraint('uq_zones_name', ['name'])

    with op.batch_alter_table('units', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_units', ['id'])
        batch_op.create_unique_constraint('uq_units_code', ['code'])
        batch_op.create_foreign_key('fk_units_zone', 'zones', ['zone_id'], ['id'])

    with op.batch_alter_table('centers', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_centers', ['id'])
        batch_op.create_unique_constraint('uq_centers_code', ['code'])
        batch_op.create_foreign_key('fk_centers_unit', 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_users', ['id'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.create_foreign_key('fk_users_unit', 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('incidents', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_incidents', ['id'])
        batch_op.create_foreign_key('fk_incidents_center', 'centers', ['center_id'], ['id'])
        batch_op.create_foreign_key('fk_incidents_unit', 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key('fk_incidents_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_profiles', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_user_profiles', ['id'])
        batch_op.create_unique_constraint('uq_user_profiles_email', ['email'])
        batch_op.create_unique_constraint('uq_user_profiles_professional_number', ['professional_number'])
        batch_op.create_foreign_key('fk_user_profiles_user', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('incidents')
    op.drop_table('users')
    op.drop_table('centers')
    op.drop_table('units')
    op.drop_table('zones')
    # ### end Alembic commands ###
