"""Add Infrastructure model

Revision ID: 74bb9fcea863
Revises: 57a86e38bb92
Create Date: 2025-01-25 17:49:53.643597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bb9fcea863'
down_revision = '57a86e38bb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_centers_unit', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('structure_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('uq_units_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_units_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_updated_at'), ['updated_at'], unique=False)
        batch_op.drop_constraint('fk_units_zone', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('structure_type')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_profiles_email', type_='unique')
        batch_op.drop_constraint('uq_user_profiles_professional_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.drop_constraint('fk_users_unit', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_zones_code', type_='unique')
        batch_op.drop_constraint('uq_zones_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_zones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_updated_at'))
        batch_op.drop_index(batch_op.f('ix_zones_created_at'))
        batch_op.create_unique_constraint('uq_zones_name', ['name'])
        batch_op.create_unique_constraint('uq_zones_code', ['code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_users_unit', 'units', ['unit_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_created_at'))
        batch_op.create_unique_constraint('uq_user_profiles_professional_number', ['professional_number'])
        batch_op.create_unique_constraint('uq_user_profiles_email', ['email'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_units_zone', 'zones', ['zone_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_units_updated_at'))
        batch_op.drop_index(batch_op.f('ix_units_created_at'))
        batch_op.create_unique_constraint('uq_units_code', ['code'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_updated_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))
        batch_op.alter_column('structure_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_centers_unit', 'units', ['unit_id'], ['id'])

    # ### end Alembic commands ###
