"""Add indexes to models

Revision ID: bddc38769ebc
Revises: add_drawn_shapes
Create Date: 2025-01-25 11:24:23.063376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddc38769ebc'
down_revision = 'add_drawn_shapes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_centers_unit', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('structure_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_incidents_center_id'), ['center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_commune'), ['commune'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_date_incident'), ['date_incident'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_date_resolution'), ['date_resolution'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_gravite'), ['gravite'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_localite'), ['localite'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_nature_cause'), ['nature_cause'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_structure_type'), ['structure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_wilaya'), ['wilaya'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('uq_units_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_units_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_units_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_zone_id'), ['zone_id'], unique=False)
        batch_op.drop_constraint('fk_units_zone', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('structure_type')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_profiles_email', type_='unique')
        batch_op.drop_constraint('uq_user_profiles_professional_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_profiles_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_job_function'), ['job_function'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_professional_number'), ['professional_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_profiles_recruitment_date'), ['recruitment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_zone_id'), ['zone_id'], unique=False)
        batch_op.drop_constraint('fk_users_unit', type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_zones_code', type_='unique')
        batch_op.drop_constraint('uq_zones_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_zones_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_zones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_zones_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_zones_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_updated_at'))
        batch_op.drop_index(batch_op.f('ix_zones_name'))
        batch_op.drop_index(batch_op.f('ix_zones_created_at'))
        batch_op.drop_index(batch_op.f('ix_zones_code'))
        batch_op.create_unique_constraint('uq_zones_name', ['name'])
        batch_op.create_unique_constraint('uq_zones_code', ['code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_users_unit', 'units', ['unit_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_zone_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_unit_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_last_login'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_recruitment_date'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_professional_number'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_job_function'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_created_at'))
        batch_op.create_unique_constraint('uq_user_profiles_professional_number', ['professional_number'])
        batch_op.create_unique_constraint('uq_user_profiles_email', ['email'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_units_zone', 'zones', ['zone_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_units_zone_id'))
        batch_op.drop_index(batch_op.f('ix_units_updated_at'))
        batch_op.drop_index(batch_op.f('ix_units_name'))
        batch_op.drop_index(batch_op.f('ix_units_created_at'))
        batch_op.drop_index(batch_op.f('ix_units_code'))
        batch_op.create_unique_constraint('uq_units_code', ['code'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_wilaya'))
        batch_op.drop_index(batch_op.f('ix_incidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_updated_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_unit_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_title'))
        batch_op.drop_index(batch_op.f('ix_incidents_structure_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_nature_cause'))
        batch_op.drop_index(batch_op.f('ix_incidents_localite'))
        batch_op.drop_index(batch_op.f('ix_incidents_gravite'))
        batch_op.drop_index(batch_op.f('ix_incidents_date_resolution'))
        batch_op.drop_index(batch_op.f('ix_incidents_date_incident'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_commune'))
        batch_op.drop_index(batch_op.f('ix_incidents_center_id'))
        batch_op.alter_column('structure_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_centers_unit', 'units', ['unit_id'], ['id'])

    # ### end Alembic commands ###
